Update eleventy build job.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -65,7 +65,13 @@ jobs:
         run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
 
       - name: Build with Eleventy
-        run: ${{ steps.detect-package-manager.outputs.runner }} eleventy
+        run: |
+          try {
+            ${{ steps.detect-package-manager.outputs.runner }} eleventy
+          } catch (err) {
+            echo "::error::${err.message}"
+            exit 1
+          }
 
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
